# -*- coding: utf-8 -*-
"""Build Gazebo SDF models for the 11 test items from docs/Stl/.

Per item: visual = original STL, collision = its convex hull (cheap physics,
heavy meshes must not kill RTF), inertia computed from the hull with the
assigned mass. Meshes are exported in mm and scaled 0.001 in SDF (meters).
Origin: XY at bounding-box center, Z=0 at the lowest point (items sit on belt).

Output tree (generated, gitignored): sim/models/items/<slug>/
Run: python scripts/build_item_models.py
"""
import sys
from pathlib import Path

import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parents[1]
STL_DIR = ROOT / "docs" / "Stl"
OUT_DIR = ROOT / "sim" / "models" / "items"

# slug -> (STL stem, mass kg). Masses assigned by common sense (docs/decisions.md);
# STL carries no mass. Refine if simulation physics looks wrong.
ITEMS = {
    "bottle": ("Бутылка", 0.8),
    "box_300x200x200": ("Короб 300х200х200", 1.5),
    "box_400x400x300": ("Короб 400х400х300", 3.0),
    "lunchbox": ("ЛанчБокс", 0.4),
    "bag": ("Мешок", 1.0),
    "detergent": ("Моющее средство", 1.5),
    "pouf": ("Пуфик", 2.0),
    "pen": ("Ручка", 0.02),
    "plate": ("Тарелка", 0.35),
    "cylinder": ("Цилиндр", 1.0),
    "helmet": ("Шлем", 0.8),
}

SDF_TEMPLATE = """<?xml version="1.0"?>
<sdf version="1.8">
  <model name="item_{slug}">
    <link name="link">
      <inertial>
        <pose>{cx:.6f} {cy:.6f} {cz:.6f} 0 0 0</pose>
        <mass>{mass}</mass>
        <inertia>
          <ixx>{ixx:.9f}</ixx><iyy>{iyy:.9f}</iyy><izz>{izz:.9f}</izz>
          <ixy>{ixy:.9f}</ixy><ixz>{ixz:.9f}</ixz><iyz>{iyz:.9f}</iyz>
        </inertia>
      </inertial>
      <collision name="collision">
        <geometry>
          <mesh><uri>meshes/collision.stl</uri><scale>0.001 0.001 0.001</scale></mesh>
        </geometry>
        <surface><friction><ode><mu>0.8</mu><mu2>0.8</mu2></ode></friction></surface>
      </collision>
      <visual name="visual">
        <geometry>
          <mesh><uri>meshes/visual.stl</uri><scale>0.001 0.001 0.001</scale></mesh>
        </geometry>
      </visual>
    </link>
  </model>
</sdf>
"""

CONFIG_TEMPLATE = """<?xml version="1.0"?>
<model>
  <name>item_{slug}</name>
  <version>1.0</version>
  <sdf version="1.8">model.sdf</sdf>
  <description>{stem} — test item, generated by scripts/build_item_models.py</description>
</model>
"""


def set_belt_origin(mesh):
    """Move a mesh IN PLACE to the model/spawn origin: XY at the bounding-box
    centre, Z=0 at the lowest point (items sit ON the belt).

    Single source of this convention: the generated models are built about this
    origin, and scripts/spawn_orientations.py measures the spawn height about the
    SAME origin. Gazebo rotates the model about it, so the two MUST agree — a
    mismatch computes the height for a different pivot than physics uses.
    """
    lo, hi = mesh.bounds
    mesh.apply_translation([-(lo[0] + hi[0]) / 2, -(lo[1] + hi[1]) / 2, -lo[2]])
    return mesh


def build_item(slug, stem, mass_kg):
    """Generate one model dir; returns stats dict for the log."""
    mesh = trimesh.load(str(STL_DIR / f"{stem}.stl"), force="mesh")
    set_belt_origin(mesh)
    # collision hull on 5mm-quantized vertices: physics wants hundreds of
    # faces, not thousands; ±2.5 mm shape error is fine for routing
    quantized = np.unique(np.round(mesh.vertices / 5.0) * 5.0, axis=0)
    hull = trimesh.Trimesh(vertices=quantized).convex_hull

    # inertia about COM, in meters/kg, computed on the hull
    hull_m = hull.copy()
    hull_m.apply_scale(0.001)
    hull_m.density = mass_kg / hull_m.volume
    inertia = hull_m.moment_inertia
    com = hull_m.center_mass

    out = OUT_DIR / slug
    (out / "meshes").mkdir(parents=True, exist_ok=True)
    mesh.export(out / "meshes" / "visual.stl")
    hull.export(out / "meshes" / "collision.stl")
    (out / "model.sdf").write_text(
        SDF_TEMPLATE.format(
            slug=slug, mass=mass_kg,
            cx=com[0], cy=com[1], cz=com[2],
            ixx=inertia[0, 0], iyy=inertia[1, 1], izz=inertia[2, 2],
            ixy=inertia[0, 1], ixz=inertia[0, 2], iyz=inertia[1, 2],
        ),
        encoding="utf-8",
    )
    (out / "model.config").write_text(
        CONFIG_TEMPLATE.format(slug=slug, stem=stem), encoding="utf-8"
    )
    return {
        "slug": slug,
        "extents_mm": mesh.extents,
        "hull_faces": len(hull.faces),
        "visual_faces": len(mesh.faces),
        "mass": mass_kg,
    }


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    for slug, (stem, mass) in ITEMS.items():
        s = build_item(slug, stem, mass)
        ext = " × ".join(f"{x:.0f}" for x in s["extents_mm"])
        print(f"{slug}: AABB {ext} mm, mass {mass} kg, "
              f"visual {s['visual_faces']} faces, hull {s['hull_faces']} faces")
    print(f"\n{len(ITEMS)} models written to {OUT_DIR}")


if __name__ == "__main__":
    main()
